Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,23 +1,26 @@
-#!/bin/bash
-
-# Check if all required parameters are provided
-if [ $# -lt 4 ]; then
-  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+#!/usr/bin/env bash
+# Checking for command-line argument
+if [ $# -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
 fi
 
-# Assign parameters to variables
+# Assigning Arguments to variables
+
 path_to_file=$1
 ip=$2
 username=$3
 path_to_ssh_key=$4
 
-# Transfer the file using scp
+
+# Disabbling Strict Host Key checking
 scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-# Check the exit status of scp
-if [ $? -eq 0 ]; then
-  echo "File transferred successfully."
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-  echo "Failed to transfer the file."
+  echo "FILE TRANSFER FAILED"
 fi
