Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,23 @@
-#!/usr/bin/env bash
-# transfers a file from a client to a server with scp
+#!/bin/bash
 
-if [ "$#" -lt 3 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+# Check if all required parameters are provided
+if [ $# -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+
+# Assign parameters to variables
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# Transfer the file using scp
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Check the exit status of scp
+if [ $? -eq 0 ]; then
+  echo "File transferred successfully."
 else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+  echo "Failed to transfer the file."
 fi
